---
# Simple Ansible Playbook for IBM Cloud Schematics
# This playbook configures the VSI created by Terraform
# Schematics automatically uses Terraform outputs as inventory

- name: Configure IBM Cloud VSI
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install essential packages
      apt:
        name:
          - nginx
          - git
          - curl
          - vim
          - htop
        state: present
      when: ansible_os_family == "Debian"

    - name: Create web directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Deploy simple web page
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>IBM Cloud Demo</title>
              <style>
                  body {
                      font-family: 'IBM Plex Sans', Arial, sans-serif;
                      background: linear-gradient(135deg, #0f62fe 0%, #0043ce 100%);
                      color: white;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      height: 100vh;
                      margin: 0;
                  }
                  .container {
                      text-align: center;
                      background: rgba(255, 255, 255, 0.1);
                      padding: 3rem;
                      border-radius: 10px;
                      backdrop-filter: blur(10px);
                  }
                  h1 { font-size: 3rem; margin-bottom: 1rem; }
                  p { font-size: 1.2rem; }
                  .info { margin-top: 2rem; font-size: 0.9rem; opacity: 0.8; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🚀 IBM Cloud VSI</h1>
                  <p>Deployed with Terraform & Configured with Ansible</p>
                  <p>via IBM Cloud Schematics</p>
                  <div class="info">
                      <p>Hostname: {{ ansible_hostname }}</p>
                      <p>OS: {{ ansible_distribution }} {{ ansible_distribution_version }}</p>
                      <p>Configured: {{ ansible_date_time.iso8601 }}</p>
                  </div>
              </div>
          </body>
          </html>
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Ensure nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Configure firewall for HTTP
      ufw:
        rule: allow
        port: '80'
        proto: tcp
      when: ansible_os_family == "Debian"

    - name: Configure firewall for HTTPS
      ufw:
        rule: allow
        port: '443'
        proto: tcp
      when: ansible_os_family == "Debian"

    - name: Display completion message
      debug:
        msg: "VSI configuration complete! Access your server at http://{{ ansible_default_ipv4.address }}"

# Made with Bob
